### ISSUE TITLE
Frontend UI 

### ISSUE THREAD

**Issue by inceptionabhishek** [Developer-Y/cs-video-courses#133]
Sir, I made the website collecting all the resources you provided, If you want to check out:
Website Link: https://inceptionabhishek.github.io/Computer-Science-Video-Resource/
Repo Link: https://github.com/inceptionabhishek/Computer-Science-Video-Resource

**Comment by Divyanshu-cmd-in-code** [comment]
I have checked and the courses are nice

**Comment by inceptionabhishek** [comment]
thanks

**Comment by krish0410** [comment]
Sir , I want to some more attractive css part in it if you are interested  please let me know

**Comment by inceptionabhishek** [comment]
> Sir , I am a beginner and i want to add some more attractive css part in it if you are interested please let me know.

yes go ahead and i am beginner too ;)

**Comment by beatboxgodgithub** [comment]
sure ty

**Comment by SatyamShukla777** [comment]
Sir, I am Beginner too and Im interested in adding some features to the website

**Comment by Developer-Y** [comment]
Hi,

Sorry for late reply.  I would like this page to do one thing well instead of doing many things poorly and creating a mess. I would like to keep focus on University level computer science courses, instead of adding tutorials. 

If the CSS etc links you wish to share are rigorous and University level, please create a pull request. If it's from some youtube tutorial, then there are thousand such links, please create a separate page for that and you may add the link in comment for others to see.

Thanks,
