### ISSUE TITLE
Paradigms of Computer Programming from Université de Louvain

### ISSUE THREAD

**Issue by stereobooster** [Developer-Y/cs-video-courses#25]
Introduction to Computer Science

[Paradigms of Computer Programming](https://www.edx.org/course/paradigms-computer-programming-louvainx-louv1-1x-1), Université catholique de Louvain, Peter Van Roy, Edx

**Comment by Developer-Y** [comment]
Instead of pointing to MOOC's, I guess its preferable to point to link from where videos can be directly viewed/downloaded instantaneously. People interested in that MOOC can then decide to look for the MOOC and earn the certificate.

For this course I have added YouTube link of videos. https://www.youtube.com/playlist?list=PLw454N-VXALSIzIe_eL5U8L4S68v2X_ak , I am sure assignments/projects in the MOOC must be good but I want to keep this list as list of video lectures than list of MOOCs.

**Comment by stereobooster** [comment]
Cool, thanks
